
# The username of your bot as set with the botfather
NATALIA_BOT_USERNAME: "@My_Natalia_Bot"

# The bot token supplied by botfather
NATALIA_BOT_TOKEN: "my-botfather-token"

# The telegram Id of the bot owner
BOT_OWNER_ID: 123456789

# Admin Telegram Ids
ADMINS:
  - 123456789  # my-telegram-user-id


# Stop words for wordcloud
WORDCLOUD_STOPWORDS:
  - dont
  - include
  - these
  - words
  - in
  - the
  - wordcloud

# Forward URLS
# URLS matching this regex will look to be forwarded to your 'feed' room
FORWARD_URLS: 'bloomberg.com|tradingview.com|coindesk.com'


# Shill Detected
# URLS of shill links to look out for to issue a warning message
SHILL_DETECTOR: 'bitmex\.com\/register\/([a-zA-Z0-9]*)|cryptofacilities\.com\/derivatives\/([a-zA-Z0-9-_]*)|bitfinex\.com\/\?refcode=([a-zA-Z0-9]*)|simplefx\.com\/\?sfx-r=([a-zA-Z0-9-_]*)|1broker\.com\/\?c=en\/action\/r&i=([a-zA-Z0-9]*)|nitrogensports\.eu\/r\/([a-zA-Z0-9]*)|binance\.com\/\?ref=([a-zA-Z0-9]*)|deribit\.com\/reg-([a-zA-Z0-9\.]*)'
# bitmex\.com\/register\/([a-zA-Z0-9]*)|
# cryptofacilities\.com\/derivatives\/([a-zA-Z0-9-_]*)|
# bitfinex\.com\/\?refcode=([a-zA-Z0-9]*)|
# simplefx\.com\/\?sfx-r=([a-zA-Z0-9-_]*)|
# 1broker\.com\/\?c=en\/action\/r&i=([a-zA-Z0-9]*)|
# nitrogensports\.eu\/r\/([a-zA-Z0-9]*)|
# binance\.com\/\?ref=([a-zA-Z0-9]*)|
# deribit\.com\/reg-([a-zA-Z0-9\.]*)


# List of matching shill links and their counter shill links to replace the offending messages with
COUNTER_SHILL:

  - title: 'Bitmex'
    match: 'bitmex\.com\/register\/([a-zA-Z0-9]*)'
    link : 'http://bitmex.whalepool.io'

  - title: 'CryptoFacilities'
    match: 'cryptofacilities\.com\/derivatives\/([a-zA-Z0-9-_]*)'
    link : 'http://cryptofacilities.whalepool.io'

  - title: 'Bitfinex'
    match: 'cryptofacilities\.com\/derivatives\/([a-zA-Z0-9-_]*)'
    link : 'http://bitfinex.whalepool.io'

  - title: 'Simplefx'
    match: 'simplefx\.com\/\?sfx-r=([a-zA-Z0-9-_]*)'
    link : 'http://simplefx.whalepool.io'

  - title: '1broker'
    match: '1broker\.com\/\?c=en\/action\/r&i=([a-zA-Z0-9]*)'
    link : 'http://1broker.whalepool.io'

  - title: 'NitrogenSports'
    match: 'nitrogensports\.eu\/r\/([a-zA-Z0-9]*)'
    link : 'http://sports.whalepool.io'

  - title: 'Binance'
    match: 'binance\.com\/\?ref=([a-zA-Z0-9]*)'
    link : 'http://binance.whalepool.io'

  - title: 'Deribit'
    match: 'deribit\.com\/reg-([a-zA-Z0-9\.]*)'
    link : 'http://deribit.whalepool.io'




MESSAGES:

  # The message displayed to new users when they join your room
  welcome:
   - "Welcome %s, I'm Nebliana, group secretary. Please PM (@Nebliana_Bot) see chat rules."

  # A special welcome message for an individually special room
  welcome_special: 'Welcome %s, this is a special chat group with a special welcome message'

  # Goodbye messages when users leave your chat
  goodbye:
   - "Smells better without ya %s"
   - "The average net worth of this group just shot up when %s left"
   - "goodbye %s. It was fun whilte it lasted"
   - "see ya %s, my sweet love"

  # If someone tries to use a command for the bot in a public channel
  # The bot will message the user telling them to pm them
  pmme:
  - "Naughty naughty %s, you know we can't talk dirty in public. PM me for that kind of talk & house rules."
  - "%s, some things a better left for behind closed doors. PM me for house rules."

  # The 'welcome' message when users first initiate pm with the bot
  start: >
   Hi %s, Welcome to Neblio

   Please click one of the links to see how i can help you:

   /rules  - See Rules

   /about - about us

   /admins - See list of admins to contact for help.

   /exchanges - See where we recommend to trade


  # The 'admin' extra control pannel welcome message
  admin_start: >
   %s, this is your admin control:

   /topstickers - posts the top 3 stickers from the last 3 days into the main room chat

   /topgif - post the top gif to whalepool + feed

   /topgifposters - post who are the top 5 gif posters

   /todayinwords - Today in words...

   /todaysusers - Wordcloiud of whos active today

   /promotets 'message' - spam / promote teamspeak with a specified message.

   /shill - spam / promote various exchanges.

   /commandstats - get the command stats since the start of the month

   /joinstats - get the join stats since the start of the month

   /whalepooloverprice - list the user gifs, user messages and user joins per hour over price


  # About page
  about: >
    *About Neblio*

    Neblio is a North American decentralized opensource BAAS platform

    Whitepaper & Roadmap: [https://nebl.io/roadmap/](https://nebl.io/roadmap/)

    Team: [https://nebl.io/about/](https://nebl.io/about/)

    Contact: [https://nebl.io/contact/](https://nebl.io/contact/)

    Slack: [https://neblio.slack.com/](https://neblio.slack.com/)

    Discord: [https://discord.gg/PFt3bVw](https://discord.gg/PFt3bVw)

    Twitter: [https://twitter.com/NeblioTeam](https://twitter.com/NeblioTeam)

    Facebook: [https://www.facebook.com/neblioteam/](https://www.facebook.com/neblioteam/)

    Reddit: [http://reddit.com/r/neblio](http://reddit.com/r/neblio)

    Telegram: [https://t.me/joinchat/GFVgz0G-oVXOIJGfFYD-vg](https://t.me/joinchat/GFVgz0G-oVXOIJGfFYD-vg)

    Neblio Telegram group is a community of Neblio users. You are welcome to join, share your opinions without excessively shilling competitors.


    /start - to go back to home


  # JSon list of admins for the '/admins' request page
  admins_json:
    "@sam_md777":
      adminOf: "Neblio Telegram"
      about  : "Sam E"
    "@JamieD1":
      adminOf: "Neblio Telegram"
      about  : "Jamie"
    "@I":
      adminOf: "Neblio Telegram"
      about  : "I Swig"
    "@Sikeolem":
      adminOf: "Neblio Telegram"
      about  : "Sike Olem"
    "@miKnutty":
      adminOf: "Neblio Telegram"
      about  : "miKnutty"
    "@Betim":
      adminOf: "Neblio Telegram"
      about  : "Betim CM"
    "@NebliodDev":
      adminOf: "Neblio Telegram"
      about  : "Nebliodev"

  # Rules
  rules: >
    *DO NOT* post any spam or referral links.

    *DO NOT* post old news, duplicate post news, crappy gifs, excessive gifs, crappy stickers, or excessive stickers. Stickers & gifs provide little value to users so their use should be sparse & selected.

    *DO NOT* post fud, unsubstantiated claims, if you're questioned to cite evidence, please provide some.

    *DO NOT* thrash other members. Respect everyones opinion as we are a community and each has their own perspective.

    *DO NOT* discuss religion or post any racist comments.

    /start - to go back to home

  # Teamspeak info request
  teamspeak: >
   Blah teamspeak blah

   /start - to go back to home


  # Telegram info request
  telegram: >
   Blah telegram blah

   /start - to go back to home

  # Chat links
  chat: >
   *Find out chat links here:* [https://nebl.io/chat/](https://nebl.io/chat/)

   *Discord*: [https://discord.gg/PFt3bVw](https://discord.gg/PFt3bVw)

   *Telegram*: [https://t.me/joinchat/GFVgz0G-oVXOIJGfFYD-vg](https://t.me/joinchat/GFVgz0G-oVXOIJGfFYD-vg)

   *Slack*: [https://neblio.slack.com](https://neblio.slack.com) | Get Invite from [https://nebl.io/chat](https://nebl.io/chat)

  # Livestream info request
  livestream: >
   Blah livestream blah

   /start - to go back to home

  # Exchanges info request
  exchanges: >
   *Binance*: [https://www.binance.com/trade.html?symbol=NEBL_BTC](https://www.binance.com/trade.html?symbol=NEBL_BTC)

   *Kucoin*: [https://www.kucoin.com/#/trade/NEBL-BTC](https://www.kucoin.com/#/trade/NEBL-BTC)

   *Cryptopia*: [https://www.cryptopia.co.nz/Exchange?market=NEBL_BTC](https://www.cryptopia.co.nz/Exchange?market=NEBL_BTC)

   *HitBTC*: [https://hitbtc.com/exchange/NEBL-to-BTC](https://hitbtc.com/exchange/NEBL-to-BTC)

   *OEX*: [https://www.oex.com/](https://www.oex.com/)

   /start - to go back to home

  # Shill exchanges / shill links
  shill: >
   Blah my shill links blah

  teamspeakbadges: >
   Blah teamspeak badges blah

  fomobot: >
   Blah fomobot blah

   /start - to go back to home


  donate: >
   Blah donate blah

   /start - to go back to home